[package]
name = "rust"
version = "0.1.0"
authors = ["marc55s <marc.schoenig@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "rust"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std", "embassy", "esp-idf-svc/native"]

std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[dependencies]
log = { version = "0.4", default-features = false }
esp-idf-svc = { version = "0.51", default-features = false }
esp-idf-hal = "0.45.2"
esp-idf-sys = "0.36.1"

anyhow = "1.0.100"
serde_json = "1.0.145"
embedded-svc = "0.28.1"
serde = "1.0.228"
smart-leds-trait = { version = "0.3", optional = true }
embedded-graphics-core = { version = "0.4", optional = true }
smart-leds = "0.4.0 "
ws2812-esp32-rmt-driver = { version = "0.13.1", features = ["smart-leds-trait", "embedded-graphics-core"] }
tokio = { version = "1.48.0", features = ["sync", "rt-multi-thread"] }

[build-dependencies]
embuild = "0.33"
